### ISSUE TITLE
Runtime exceptions with 3.4.2-SNAPSHOT: prebuilt release and build from source

### ISSUE THREAD

**Issue by vppiet** [universAAL/distro.karaf#3]
Hi! I'm getting runtime exceptions while running both prebuilt 3.4.2-SNAPSHOT release and version built from current assembly branch. Logs have been attached to both cases. Source of earlier version (3.4.1-SNAPSHOT) builds and runs fine.

To be honest, my knowledge of universAAL and Karaf is still on an introductionary level and I was hoping you can push me into right direction e.g. do any configs need modifications. Thanks!

## Prebuilt 3.4.2-SNAPSHOT release
The release was downloaded from [here](https://github.com/universAAL/distro.karaf/releases/tag/3.4.1-SNAPSHOT). (Tag must be wrong here since the release itself is 3.4.2-SNAPSHOT.). Run without any modifications. On boot, Karaf notifies that `bin/setenv` is not found and cannot start `jslp.osgi` bundle:

```
$ ./karaf
: not found: /home/ville/projects/distro.karaf-3.4.2-SNAPSHOT/bin/setenv:
...
karaf@uAAL>ERROR: Bundle jslp.osgi [62] Error starting mvn:org.universAAL.thirdparty/jslp.osgi/3.4.2-SNAPSHOT (org.osgi.framework.BundleException: Activator start error in bundle jslp.osgi [62].)
java.lang.NoClassDefFoundError: Could not initialize class ch.ethz.iks.slp.impl.SLPCore
```

No features seem to install on boot. On exit, exceptions are raised:

```
ERROR: Bundle mw.managers.space.osgi [79] Error stopping bundle. (java.lang.NullPointerException)
...
ERROR: Bundle mw.managers.space.osgi [79] Error stopping mvn:org.universAAL.middleware/mw.managers.space.osgi/3.4.2-SNAPSHOT (org.osgi.framework.BundleException: Activator stop error in bundle mw.managers.space.osgi [79].)
...
Exception in thread "Thread-16" java.lang.IllegalStateException: Invalid BundleContext.
```

[log-prebuilt_distro.txt](https://github.com/universAAL/distro.karaf/files/3137770/log-prebuilt_distro.txt)

## Built from source
Builds without errors. Run without any modifications. On boot, expections are raised:

```
$ ./karaf
...
ERROR: Bundle mw.container.osgi [72] EventDispatcher: Error during dispatch. (java.lang.RuntimeException: java.lang.NullPointerException)
...
ERROR: Bundle mw.managers.tenant.osgi [82] EventDispatcher: Error during dispatch. (java.lang.NullPointerException)
...
ERROR: Bundle mw.connectors.deploy.karaf.osgi [75] Error starting/stopping bundle. (org.osgi.framework.BundleException: Unresolved constraint in bundle mw.connectors.deploy.karaf.osgi [75]: Unable to resolve 75.0: missing requirement [75.0] osgi.wiring.package; (osgi.wiring.package=org.universAAL.middleware.interfaces.mpa.model))
org.osgi.framework.BundleException: Unresolved constraint in bundle mw.connectors.deploy.karaf.osgi [75]: Unable to resolve 75.0: missing requirement [75.0] osgi.wiring.package; (osgi.wiring.package=org.universAAL.middleware.interfaces.mpa.model)
```

No features seem to install on boot.

[log-assembly_repository-built_distro.txt](https://github.com/universAAL/distro.karaf/files/3137778/log-assembly_repository-built_distro.txt)

**Comment by Alfiva** [comment]
Hi Ville,
Are you using Windows or Linux? As you point out, it looks like it cannot find the "setenv" script, which should be in the /bin folder of Karaf, whether you downloaded it or built it. That script does different things depending on OS, but both related to encoding. Maybe that influences the further execution.
From my side I would recommend the first step to be finding out why "setenv" is not found. Perhaps you could try putting Karaf somewhere else that is not your personal folder, or running the Karaf script as admin.

**Comment by vppiet** [comment]
Hello, Alfiva!

Thank you for your reply. I'm using Linux. Details:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-48-generic", arch: "amd64", family: "unix"
```

Yes, not finding `setenv` might be related to path resolving. I'll try to investigate that.

What about the case where distro is built from source? This issue does not seem to be linked to `setenv` - rather to a missing dependency. For me, it would be ideal to be able to build a distro with my own features. I can, of course, fallback to 3.4.1-SNAPSHOT since it simply builds and works. I might be missing something and my know-how is minimal with these things so I appreciate any assistance greatly. :)

**Comment by Alfiva** [comment]
I'm not familiar with the Linux version, but asking around I got some possible fixes (for the downloaded distro):
a) Disable networking
b) Edit the Karaf script to not try to find setenv, and do setenv's job yourself: Set the Java options -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dnet.slp.port=5555
c) Set the appropriate IP injgroups property in etc/system.properties: jgroups.bind_addr={ip}

**Comment by amedranogil** [comment]
just corrections:

a) is reffered to https://github.com/universAAL/platform/wiki/Configuration-Parameters#Run_universAAL_without_network

c) is putting your actual IP in etc/system.properties for both net.slp.interfaces and jgroups.bind_addr for some reason these components are not capable of getting the correct IP for certain linux distributions; you may even have to set them in the command line of karaf for them to work.

**Comment by amedranogil** [comment]
Just comments,

a) reffers to https://github.com/universAAL/platform/wiki/Configuration-Parameters#Run_universAAL_without_network

c) you need to probably set Both net.slp.interfaces and jgroups.bind_addr to your IP (follow a)'s instructions but with your IP); for some reason these 3rd party components cannot find the correct IP on certain linux distros

**Comment by amedranogil** [comment]
Be careful, 
3.4.1-SNAPSHOT and 3.4.2-SNAPSHOT are utterly incompatible!
3.4.2-SNAPSHOT pre release is not ready yet -> use source build; we need to check if we can replicate your issue.
We need to check 3.4.1-SNAPSHOT pre-release to see if there are any problems with it.

**Comment by vppiet** [comment]
Thank you, @Alfiva and @amedranogil, for your suggestions. Unfortunately, disabling networking (uncommenting net.slp.interfaces and jgroups.bind_addr from system.properties file) and setting Java options (encoding seems to be the most important) had none or little effect. Both build from source and downloaded release wouldn't run without exceptions.

However on Windows 10, downloaded (zipped) release deploys and overall seems to run fine. A built from source doesn't - although it builds without failures. This again is on Windows.

Apologies, I have little input for this issue here. I can always try other Linux distributions. It just seems odd that 3.4.1-SNAPSHOT works great on my Linux distribution.

**Comment by amedranogil** [comment]
please use pastebin to share your exceptions with us, I am unable to replicate the issue.

**Comment by amedranogil** [comment]
It seems that the bundles are, for whatever reason, not started in the correct order. i.e: the karaf is not following the start level process for the feature.
See if removing the data folder helps.

**Comment by vppiet** [comment]
Hi @amedranogil,

> please use pastebin to share your exceptions with us, I am unable to replicate the issue.

Here is my installation and deployment process from cloning the repository and running `mvn install` onwards:

[bash.log](https://github.com/universAAL/distro.karaf/files/3275417/bash.log)
[jGroups.log](https://github.com/universAAL/distro.karaf/files/3275418/jGroups.log)
[karaf.log](https://github.com/universAAL/distro.karaf/files/3275419/karaf.log)
[uAAL.log](https://github.com/universAAL/distro.karaf/files/3275420/uAAL.log)
[uAAL-MW.log](https://github.com/universAAL/distro.karaf/files/3275421/uAAL-MW.log)

This is without setting Java options manually and modifying any settings.

> See if removing the data folder helps.

Removing the data folder does not seem to help. Either the same exceptions are raised or no output is produced to Karaf's command line. This depends at which point - before or after the first deployment - the folder is removed.

I'll give it a another go on a fresh Ubuntu 18.04 with a clean Maven local repository.

**Comment by vppiet** [comment]
Unfortunately, I had no luck Ubuntu 18.04 and Oracle JDK 8 (proposed in another conversation). This should be reproducible in a clean VirtualBox installation of Ubuntu Desktop 18.04:

1) Download latest Oracle Java 8 JDK, set JAVA_HOME env variable, add bin folder to PATH.
2) Download latest Maven, add bin folder to PATH.
3) Clone distro.karaf repository.
4) Run `mvn install`. Build is a success.
5) Chmod assembly/bin/ scripts as runnable.
6) Run assembly/bin/karaf.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T22:00:29+03:00)
Maven home: /home/ville/Software/apache-maven-3.6.1
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /home/ville/Software/jdk1.8.0_212/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-25-generic", arch: "amd64", family: "unix"
```

[bash.log](https://github.com/universAAL/distro.karaf/files/3382032/bash.log)
[jGroups.log](https://github.com/universAAL/distro.karaf/files/3382034/jGroups.log)
[karaf.log](https://github.com/universAAL/distro.karaf/files/3382035/karaf.log)
[uAAL.log](https://github.com/universAAL/distro.karaf/files/3382036/uAAL.log)
[uAAL-MW.log](https://github.com/universAAL/distro.karaf/files/3382037/uAAL-MW.log)

**Comment by Tkarius** [comment]
I could not replicate this issue on TUAS side anymore today. We should consider this issue solved and close it.

-Tommi
