### ISSUE TITLE
Exceptions during runtime and inability to install any features (karaf.distro 3.4.2)

### ISSUE THREAD

**Issue by xg-iti** [universAAL/distro.karaf#4]
I have exceptions during runtime of uAAL karaf.distro and I'm not able to install any features.

My system is Ubuntu 16.04 and I use Java 8.

```
$ java -version 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

I've built and run the karaf.distro (3.4.2) using the following commands

```
git clone https://github.com/universAAL
cd distro.karaf 
mvn install
cd target/assembly
chmod u+x bin/karaf
bin/karaf
```

On the first run karaf seems to run ok, but when run any command e.g feature:list , it is returned that command is unavailable, as depicted in image bellow
![Screenshot from 2020-01-23 11-58-25](https://user-images.githubusercontent.com/60218772/72979396-e8726080-3de0-11ea-85db-c74f7c452d1a.png)
By pressing Ctl+D to terminale the karaf, terminal doesn't responds and have to close it manually.

On every other run, exceptions appear at first, but then using Ctl+C , karaf command prompt appears where I can enter commands. Although, I am not able to install features using feature:install
I attach you the output of my terminal
[second run on terminal.txt](https://github.com/universAAL/distro.karaf/files/4102739/second.run.on.terminal.txt)

Bellow are listed all the active packages, noted that Deploy Connector Karaf is not active, but installed.
![image_2020_01_22T15_19_36_313Z](https://user-images.githubusercontent.com/60218772/72979971-363b9880-3de2-11ea-873d-807335c099a4.png)

I also attach you terminal output on mvn install in case it's useful
[maven terminal build output.txt](https://github.com/universAAL/distro.karaf/files/4102745/maven.terminal.build.output.txt)

and all the logs found under data/log folder
[karaf.log](https://github.com/universAAL/distro.karaf/files/4102749/karaf.log)
[uAAL.log](https://github.com/universAAL/distro.karaf/files/4102750/uAAL.log)
[uAAL-MW.log](https://github.com/universAAL/distro.karaf/files/4102751/uAAL-MW.log)
[jGroups.log](https://github.com/universAAL/distro.karaf/files/4102752/jGroups.log)

**Comment by Alfiva** [comment]
It may have to do with this, as shown in the log:

Could not transfer artifact org.apache.karaf.features:spring:xml:features:3.0.9 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file: http://repo1.maven.org/maven2/org/apache/karaf/features/spring/3.0.9/spring-3.0.9-features.xml. Return code is: 501 , ReasonPhrase:HTTPS Required.

We are aware that since January 15th, Maven central can only be accessed through HTTPS. We are in the process of updating references in our POMs. We may update the main universAAL POM now to try to solve this, while we look for further references. Just wait for a bit and we'll come back to it.
Thanks.

**Comment by Alfiva** [comment]
Please try again now that we have updated several references to Maven Central. Do a `mvn clean install` from `distro.karaf` to start from scratch and check if it works.

**Comment by xg-iti** [comment]
The problem related to 501 status code is solved.

Although I cannot still install any features and there are exceptions that with: Bundle mw.connectors.deploy.karaf.osgi [67] and Bundle mw.bus.context.osgi [79]

Here is the terminal output on mvn install in case it's useful
[maven terminal build output.log](https://github.com/universAAL/distro.karaf/files/4128194/maven.terminal.build.output.log)

And the terminal output after the first run:
[first run.txt](https://github.com/universAAL/distro.karaf/files/4128205/first.run.txt)

[karaf.log](https://github.com/universAAL/distro.karaf/files/4128221/karaf.log)
[uAAL.log](https://github.com/universAAL/distro.karaf/files/4128222/uAAL.log)
[uAAL-MW.log](https://github.com/universAAL/distro.karaf/files/4128223/uAAL-MW.log)

**Comment by amedranogil** [comment]
mw.connectors.deploy.karaf.osgi is most probably not needed, to make it work we need to update karaf dependency of this component (in mw source), alternativelly we can remove it from the feature (have it as an optional feature). On the mean time if it still fail, you may continue without it.

mw.bus.context.osgi should work, We need to review exactly why it is not working.

**Comment by Alfiva** [comment]
It looks like Karaf does not install all of its own bundles. Can you please post the output of the full list of bundles with `list -t 0` ? Also, just to be sure, send the content of file org.ops4j.pax.url.mvn.cfg in the etc folder.

**Comment by xg-iti** [comment]
I attach you the requested files:

[list -t 0](https://github.com/universAAL/distro.karaf/files/4133002/list.output.txt)
[org.ops4j.pax.url.mvn.cfg](https://github.com/universAAL/distro.karaf/files/4133007/org.ops4j.pax.url.mvn.cfg.txt)

Thanks

**Comment by Alfiva** [comment]
I have run a clean distro.karaf (from Windows though) and compared the bundles, and found that your instance is missing the following bundles:

```
37 | Active   |  30 | 3.0.9           | Apache Karaf :: ConfigAdmin :: Core
38 | Active   |  30 | 3.0.9           | Apache Karaf :: ConfigAdmin :: Commands
48 | Active   |  30 | 1.0.0.v20110524 | Region Digraph
49 | Active   |  30 | 3.0.9           | Apache Karaf :: Region :: Persistence
50 | Active   |  30 | 3.0.9           | Apache Karaf :: Region :: Shell Commands
51 | Active   |  30 | 3.0.9           | Apache Karaf :: Package :: Core
52 | Active   |  30 | 3.0.9           | Apache Karaf :: Package :: Commands
54 | Active   |  30 | 3.0.9           | Apache Karaf :: KAR :: Command
55 | Active   |  30 | 3.0.9           | Apache Karaf :: Deployer :: Karaf Archive (.kar)
56 | Active   |  30 | 2.0.7           | Apache MINA Core
57 | Active   |  30 | 3.0.9           | Apache Karaf :: Shell :: SSH
```

We will try to figure out why is that.

I also wanted to check the list of repositories in org.ops4j.pax.url.mvn.cfg in case they were rendered different in Linux, but they are the same. Nevertheless, there is a repository commented out in that file, but since it is listed in a single line, it is not parsed correctly. Just in case it could be messing with the rest of the line (I doubt it) you could remove
`#    http://zodiac.springsource.com/maven/bundles/release@id=gemini,` 
from the last line of that file.

**Comment by xg-iti** [comment]
By removing the text you referred from last line indeed solved the exception related to mw.connectors.deploy.karaf.osgi [67]. 
Now when I try to install a feature, as it's shown in the terminal output I attach, the error is related to context bus, that i guess it's core component and it's logical to fail. Also I have to note that feature:install takes some time to produce output, that I suppose indicate that processes are running in the background, something that didn't happen before.

[terminal output after removed source](https://github.com/universAAL/distro.karaf/files/4133266/terminal.output.after.removed.source.txt)
[list -t 0](https://github.com/universAAL/distro.karaf/files/4133265/list.output.removed.commented.source.txt)
[new org.ops4j.pax.url.mvn.cfg](https://github.com/universAAL/distro.karaf/files/4133274/org.ops4j.pax.url.mvn.cfg.2.txt)

**Comment by Alfiva** [comment]
At this point I would suggest starting from scratch again, only this time remove the commented repository from the line before running Karaf for the first time. Please note that when everything works OK it takes some time for all bundles to start up, the first time.

**Comment by xg-iti** [comment]
Thank Alfiva, all problems seem to be resolved now, I can install features and no exceptions occur during runtime.
I've remove the line `#    http://zodiac.springsource.com/maven/bundles/release@id=gemini, \`
from `distro.karaf/src/main/filtered-resources/etc/org.ops4j.pax.url.mvn.cfg` and after I did a clean maven build.  

[build and runtime terminal output](https://github.com/universAAL/distro.karaf/files/4133437/terminal.output.txt)

**Comment by amedranogil** [comment]
maybe we should commit this change, 
What would that repository would be used for?

**Comment by Alfiva** [comment]
I am not sure, I think it is part of the Karaf defaults, but perhaps it was used for some rare dependencies of less used modules... right now I do not remember any.
What I don't know is why is this one suppossed to be commented out in the latest version of org.ops4j.pax.url.mvn.cfg, as oppossed to previous versions where it was included.
So the solution would be to either remove it or uncomment it, but yes, we should commit it.

**Comment by Alfiva** [comment]
Just a quick update: I tried accessing the repository and apparently it is not available (name not resolved). It is either temporary down, not accessible through web, or simply no longer exists.
