### ISSUE TITLE
Empty lines in "setenv" script produce errors when Dockerizing

### ISSUE THREAD

**Issue by Alfiva** [universAAL/distro.karaf#5]
We build the Docker image of the distro using the Dockerfile. However when attempting to run it we get some weird error messages: Several ": not foundaraf: 18: /uAAL/bin/setenv:" and also a "java.lang.NumberFormatException: For input string: "5555".

This is solved by removing all empty/blank lines in the "setenv" scripts in assembly/bin. We are not sure but it may be due to file/return encoding in Windows vs Linux (we use Docker Desktop for Windows with Linux containers).

I assume there is no problem in removing those lines (for other OSs for instance)?

**Comment by amedranogil** [comment]
yes, 
If removing empty lines works, please commit the change in assembly

**Comment by Alfiva** [comment]
Fixed in 8c62ceb7f7714ad27667dd578b7d6a5b402458e4
